# Generated by Django 3.2.1 on 2021-05-05 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('course_author', models.CharField(max_length=100)),
                ('pub_date', models.DateField()),
                ('course_type', models.CharField(max_length=100)),
            ],
        ),
    ]
