# Generated by Django 3.2.1 on 2021-05-10 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aialieneer', '0003_auto_20210510_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_title',
            field=models.CharField(max_length=100),
        ),
    ]
