# Generated by Django 3.2.2 on 2021-05-11 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aialieneer', '0004_alter_course_course_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('post_author', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('post_type', models.CharField(max_length=100)),
                ('image', models.ImageField(default='', upload_to='aialieneer/images')),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
    ]
